-- Bring legacy MenuItem table to the current Prisma schema.
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "caloriesPer100g" DOUBLE PRECISION;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "defaultPortionGrams" DOUBLE PRECISION NOT NULL DEFAULT 100;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "proteinPer100g" DOUBLE PRECISION;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "fatPer100g" DOUBLE PRECISION;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "recipeText" TEXT;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "barcode" TEXT;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "barcodeAliases" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "MenuItem_userEmail_barcode_key"
  ON "MenuItem"("userEmail", "barcode");
